# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - master
    - features/*

variables:
  buildConfiguration: 'Release'

jobs:
- template: build_jobs.yml
  parameters:
    buildConfiguration: $(buildConfiguration)

#steps:
#- template: build_jobs.yml
#  parameters:
#    buildConfiguration: $(buildConfiguration)

#pool:
#  vmImage: 'Ubuntu-16.04'

#jobs:
#- job: Build
#  steps:
#  - script: dotnet build --configuration $(buildConfiguration)
#    displayName: 'dotnet build $(buildConfiguration)'
#  - script: dotnet test $(buildConfiguration) --no-build
#    displayName: 'dotnet test $(buildConfiguration)'
#  - script: echo hello world after build
#  pool:
#    vmImage: 'Ubuntu-16.04'

pr:
- master
- features/*